# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0002_auto_20171112_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=3131),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
