# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0003_auto_20171112_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
