# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0005_auto_20171112_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date),
        ),
    ]
