# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0006_auto_20171112_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='dob',
        ),
    ]
